/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CleaningStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'deepClean' : IDL.Null,
  'standardClean' : IDL.Null,
  'other' : IDL.Text,
  'woodPolishing' : IDL.Null,
  'upholsteryClean' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const CleaningAppointment = IDL.Record({
  'id' : IDL.Text,
  'status' : CleaningStatus,
  'serviceType' : ServiceType,
  'contact' : ContactInfo,
  'clientName' : IDL.Text,
  'scheduledTime' : Time,
  'employeeId' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Nat,
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'sales' : IDL.Null,
  'cleaner' : IDL.Null,
  'woodworker' : IDL.Null,
  'restorer' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : ContactInfo,
  'name' : IDL.Text,
  'role' : Role,
});
export const RestorationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const RestorationProject = IDL.Record({
  'id' : IDL.Text,
  'status' : RestorationStatus,
  'completionDate' : Time,
  'cost' : IDL.Nat,
  'description' : IDL.Text,
  'comments' : IDL.Text,
  'clientContact' : ContactInfo,
  'assignedEmployee' : IDL.Opt(IDL.Text),
});
export const SaleTransaction = IDL.Record({
  'id' : IDL.Text,
  'customerContact' : ContactInfo,
  'item' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Participant = IDL.Record({
  'contactInfo' : ContactInfo,
  'name' : IDL.Text,
  'registeredAt' : Time,
});
export const WorkshopType = IDL.Variant({
  'kids' : IDL.Null,
  'adults' : IDL.Null,
  'skillLevel' : IDL.Null,
});
export const WorkshopActivity = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(Participant),
  'topic' : IDL.Text,
  'scheduledTime' : Time,
  'instructor' : IDL.Text,
  'type' : WorkshopType,
  'details' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCleaningAppointment' : IDL.Func([CleaningAppointment], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addRestorationProject' : IDL.Func([RestorationProject], [], []),
  'addSale' : IDL.Func([SaleTransaction], [], []),
  'addWorkshopActivity' : IDL.Func([WorkshopActivity], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCleaningAppointments' : IDL.Func(
      [],
      [IDL.Vec(CleaningAppointment)],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllRestorationProjects' : IDL.Func(
      [],
      [IDL.Vec(RestorationProject)],
      ['query'],
    ),
  'getAllSales' : IDL.Func([], [IDL.Vec(SaleTransaction)], ['query']),
  'getAllWorkshopActivities' : IDL.Func(
      [],
      [IDL.Vec(WorkshopActivity)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCleaningAppointment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CleaningAppointment)],
      [],
    ),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], []),
  'getRestorationProject' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RestorationProject)],
      [],
    ),
  'getSale' : IDL.Func([IDL.Text], [IDL.Opt(SaleTransaction)], []),
  'getWorkshopActivity' : IDL.Func([IDL.Text], [IDL.Opt(WorkshopActivity)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'validateAdminOrRole' : IDL.Func([IDL.Principal, Role], [], ['oneway']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CleaningStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'deepClean' : IDL.Null,
    'standardClean' : IDL.Null,
    'other' : IDL.Text,
    'woodPolishing' : IDL.Null,
    'upholsteryClean' : IDL.Null,
  });
  const ContactInfo = IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text });
  const Time = IDL.Int;
  const CleaningAppointment = IDL.Record({
    'id' : IDL.Text,
    'status' : CleaningStatus,
    'serviceType' : ServiceType,
    'contact' : ContactInfo,
    'clientName' : IDL.Text,
    'scheduledTime' : Time,
    'employeeId' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'sales' : IDL.Null,
    'cleaner' : IDL.Null,
    'woodworker' : IDL.Null,
    'restorer' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : ContactInfo,
    'name' : IDL.Text,
    'role' : Role,
  });
  const RestorationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const RestorationProject = IDL.Record({
    'id' : IDL.Text,
    'status' : RestorationStatus,
    'completionDate' : Time,
    'cost' : IDL.Nat,
    'description' : IDL.Text,
    'comments' : IDL.Text,
    'clientContact' : ContactInfo,
    'assignedEmployee' : IDL.Opt(IDL.Text),
  });
  const SaleTransaction = IDL.Record({
    'id' : IDL.Text,
    'customerContact' : ContactInfo,
    'item' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Participant = IDL.Record({
    'contactInfo' : ContactInfo,
    'name' : IDL.Text,
    'registeredAt' : Time,
  });
  const WorkshopType = IDL.Variant({
    'kids' : IDL.Null,
    'adults' : IDL.Null,
    'skillLevel' : IDL.Null,
  });
  const WorkshopActivity = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(Participant),
    'topic' : IDL.Text,
    'scheduledTime' : Time,
    'instructor' : IDL.Text,
    'type' : WorkshopType,
    'details' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCleaningAppointment' : IDL.Func([CleaningAppointment], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addRestorationProject' : IDL.Func([RestorationProject], [], []),
    'addSale' : IDL.Func([SaleTransaction], [], []),
    'addWorkshopActivity' : IDL.Func([WorkshopActivity], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCleaningAppointments' : IDL.Func(
        [],
        [IDL.Vec(CleaningAppointment)],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllRestorationProjects' : IDL.Func(
        [],
        [IDL.Vec(RestorationProject)],
        ['query'],
      ),
    'getAllSales' : IDL.Func([], [IDL.Vec(SaleTransaction)], ['query']),
    'getAllWorkshopActivities' : IDL.Func(
        [],
        [IDL.Vec(WorkshopActivity)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCleaningAppointment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CleaningAppointment)],
        [],
      ),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], []),
    'getRestorationProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RestorationProject)],
        [],
      ),
    'getSale' : IDL.Func([IDL.Text], [IDL.Opt(SaleTransaction)], []),
    'getWorkshopActivity' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkshopActivity)],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'validateAdminOrRole' : IDL.Func([IDL.Principal, Role], [], ['oneway']),
  });
};

export const init = ({ IDL }) => { return []; };