/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CleaningAppointment {
  'id' : string,
  'status' : CleaningStatus,
  'serviceType' : ServiceType,
  'contact' : ContactInfo,
  'clientName' : string,
  'scheduledTime' : Time,
  'employeeId' : string,
  'notes' : string,
  'price' : bigint,
}
export type CleaningStatus = { 'scheduled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface ContactInfo { 'email' : string, 'phone' : string }
export interface Employee {
  'id' : string,
  'contactInfo' : ContactInfo,
  'name' : string,
  'role' : Role,
}
export type ExternalBlob = Uint8Array;
export interface Participant {
  'contactInfo' : ContactInfo,
  'name' : string,
  'registeredAt' : Time,
}
export interface RestorationProject {
  'id' : string,
  'status' : RestorationStatus,
  'completionDate' : Time,
  'cost' : bigint,
  'description' : string,
  'comments' : string,
  'clientContact' : ContactInfo,
  'assignedEmployee' : [] | [string],
}
export type RestorationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'sales' : null } |
  { 'cleaner' : null } |
  { 'woodworker' : null } |
  { 'restorer' : null };
export interface SaleTransaction {
  'id' : string,
  'customerContact' : ContactInfo,
  'item' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'price' : bigint,
}
export type ServiceType = { 'deepClean' : null } |
  { 'standardClean' : null } |
  { 'other' : string } |
  { 'woodPolishing' : null } |
  { 'upholsteryClean' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkshopActivity {
  'id' : string,
  'participants' : Array<Participant>,
  'topic' : string,
  'scheduledTime' : Time,
  'instructor' : string,
  'type' : WorkshopType,
  'details' : string,
  'price' : bigint,
}
export type WorkshopType = { 'kids' : null } |
  { 'adults' : null } |
  { 'skillLevel' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCleaningAppointment' : ActorMethod<[CleaningAppointment], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addRestorationProject' : ActorMethod<[RestorationProject], undefined>,
  'addSale' : ActorMethod<[SaleTransaction], undefined>,
  'addWorkshopActivity' : ActorMethod<[WorkshopActivity], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCleaningAppointments' : ActorMethod<[], Array<CleaningAppointment>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllRestorationProjects' : ActorMethod<[], Array<RestorationProject>>,
  'getAllSales' : ActorMethod<[], Array<SaleTransaction>>,
  'getAllWorkshopActivities' : ActorMethod<[], Array<WorkshopActivity>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCleaningAppointment' : ActorMethod<[string], [] | [CleaningAppointment]>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getRestorationProject' : ActorMethod<[string], [] | [RestorationProject]>,
  'getSale' : ActorMethod<[string], [] | [SaleTransaction]>,
  'getWorkshopActivity' : ActorMethod<[string], [] | [WorkshopActivity]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], undefined>,
  'validateAdminOrRole' : ActorMethod<[Principal, Role], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];