/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Participant {
    contactInfo: ContactInfo;
    name: string;
    registeredAt: Time;
}
export interface WorkshopActivity {
    id: string;
    participants: Array<Participant>;
    topic: string;
    scheduledTime: Time;
    instructor: string;
    type: WorkshopType;
    details: string;
    price: bigint;
}
export type Time = bigint;
export type ServiceType = {
    __kind__: "deepClean";
    deepClean: null;
} | {
    __kind__: "standardClean";
    standardClean: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "woodPolishing";
    woodPolishing: null;
} | {
    __kind__: "upholsteryClean";
    upholsteryClean: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RestorationProject {
    id: string;
    status: RestorationStatus;
    completionDate: Time;
    cost: bigint;
    description: string;
    comments: string;
    clientContact: ContactInfo;
    assignedEmployee?: string;
}
export interface RestaurantOrder {
    id: string;
    status: string;
    kitchenStatus: string;
    createdAt: bigint;
    tableId: string;
    tableNumber: string;
    restaurantId: string;
    updatedAt: bigint;
    itemsJson: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MenuSnapshot {
    menuJson: string;
    restaurantId: string;
    timestamp: bigint;
}
export interface CleaningAppointment {
    id: string;
    status: CleaningStatus;
    serviceType: ServiceType;
    contact: ContactInfo;
    clientName: string;
    scheduledTime: Time;
    employeeId: string;
    notes: string;
    price: bigint;
}
export interface SaleTransaction {
    id: string;
    customerContact: ContactInfo;
    item: string;
    timestamp: Time;
    quantity: bigint;
    price: bigint;
}
export interface Employee {
    id: string;
    contactInfo: ContactInfo;
    name: string;
    role: Role;
}
export interface ContactInfo {
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum CleaningStatus {
    scheduled = "scheduled",
    pending = "pending",
    completed = "completed"
}
export enum RestorationStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum Role {
    manager = "manager",
    admin = "admin",
    sales = "sales",
    cleaner = "cleaner",
    woodworker = "woodworker",
    restorer = "restorer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkshopType {
    kids = "kids",
    adults = "adults",
    skillLevel = "skillLevel"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCleaningAppointment(appointment: CleaningAppointment): Promise<void>;
    addEmployee(employee: Employee): Promise<void>;
    addRestorationProject(project: RestorationProject): Promise<void>;
    addSale(sale: SaleTransaction): Promise<void>;
    addWorkshopActivity(activity: WorkshopActivity): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllCleaningAppointments(): Promise<Array<CleaningAppointment>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllRestorationProjects(): Promise<Array<RestorationProject>>;
    getAllSales(): Promise<Array<SaleTransaction>>;
    getAllWorkshopActivities(): Promise<Array<WorkshopActivity>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCleaningAppointment(id: string): Promise<CleaningAppointment | null>;
    getEmployee(id: string): Promise<Employee | null>;
    getMenuSnapshot(restaurantId: string): Promise<MenuSnapshot | null>;
    getRestaurantOrderHistory(orderId: string): Promise<Array<RestaurantOrder> | null>;
    getRestaurantOrders(restaurantId: string): Promise<Array<RestaurantOrder>>;
    getRestaurantOrdersByStatus(restaurantId: string, status: string): Promise<Array<RestaurantOrder>>;
    getRestorationProject(id: string): Promise<RestorationProject | null>;
    getSale(id: string): Promise<SaleTransaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkshopActivity(id: string): Promise<WorkshopActivity | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMenuSnapshot(restaurantId: string, menuJson: string): Promise<void>;
    searchRestaurantOrders(restaurantId: string, searchTerm: string): Promise<Array<RestaurantOrder>>;
    submitRestaurantOrder(order: RestaurantOrder): Promise<void>;
    updateRestaurantOrderStatus(orderId: string, kitchenStatus: string, orderStatus: string): Promise<boolean>;
    uploadFile(metadata: string, file: ExternalBlob): Promise<void>;
}
import type { CleaningAppointment as _CleaningAppointment, CleaningStatus as _CleaningStatus, ContactInfo as _ContactInfo, Employee as _Employee, ExternalBlob as _ExternalBlob, MenuSnapshot as _MenuSnapshot, Participant as _Participant, RestaurantOrder as _RestaurantOrder, RestorationProject as _RestorationProject, RestorationStatus as _RestorationStatus, Role as _Role, SaleTransaction as _SaleTransaction, ServiceType as _ServiceType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkshopActivity as _WorkshopActivity, WorkshopType as _WorkshopType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCleaningAppointment(arg0: CleaningAppointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCleaningAppointment(to_candid_CleaningAppointment_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCleaningAppointment(to_candid_CleaningAppointment_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_Employee_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_Employee_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRestorationProject(arg0: RestorationProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRestorationProject(to_candid_RestorationProject_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRestorationProject(to_candid_RestorationProject_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSale(arg0: SaleTransaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addWorkshopActivity(arg0: WorkshopActivity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkshopActivity(to_candid_WorkshopActivity_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkshopActivity(to_candid_WorkshopActivity_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllCleaningAppointments(): Promise<Array<CleaningAppointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCleaningAppointments();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCleaningAppointments();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRestorationProjects(): Promise<Array<RestorationProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestorationProjects();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestorationProjects();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSales(): Promise<Array<SaleTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return result;
        }
    }
    async getAllWorkshopActivities(): Promise<Array<WorkshopActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkshopActivities();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkshopActivities();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCleaningAppointment(arg0: string): Promise<CleaningAppointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCleaningAppointment(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCleaningAppointment(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuSnapshot(arg0: string): Promise<MenuSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuSnapshot(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuSnapshot(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantOrderHistory(arg0: string): Promise<Array<RestaurantOrder> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantOrderHistory(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantOrderHistory(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantOrders(arg0: string): Promise<Array<RestaurantOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantOrders(arg0);
            return result;
        }
    }
    async getRestaurantOrdersByStatus(arg0: string, arg1: string): Promise<Array<RestaurantOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantOrdersByStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantOrdersByStatus(arg0, arg1);
            return result;
        }
    }
    async getRestorationProject(arg0: string): Promise<RestorationProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestorationProject(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestorationProject(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSale(arg0: string): Promise<SaleTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkshopActivity(arg0: string): Promise<WorkshopActivity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkshopActivity(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkshopActivity(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveMenuSnapshot(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMenuSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMenuSnapshot(arg0, arg1);
            return result;
        }
    }
    async searchRestaurantOrders(arg0: string, arg1: string): Promise<Array<RestaurantOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurantOrders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurantOrders(arg0, arg1);
            return result;
        }
    }
    async submitRestaurantOrder(arg0: RestaurantOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRestaurantOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRestaurantOrder(arg0);
            return result;
        }
    }
    async updateRestaurantOrderStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurantOrderStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurantOrderStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CleaningAppointment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CleaningAppointment): CleaningAppointment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_CleaningStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CleaningStatus): CleaningStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RestorationProject_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestorationProject): RestorationProject {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_RestorationStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestorationStatus): RestorationStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_WorkshopActivity_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkshopActivity): WorkshopActivity {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_WorkshopType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkshopType): WorkshopType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CleaningAppointment]): CleaningAppointment | null {
    return value.length === 0 ? null : from_candid_CleaningAppointment_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuSnapshot]): MenuSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_RestaurantOrder>]): Array<RestaurantOrder> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestorationProject]): RestorationProject | null {
    return value.length === 0 ? null : from_candid_RestorationProject_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleTransaction]): SaleTransaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkshopActivity]): WorkshopActivity | null {
    return value.length === 0 ? null : from_candid_WorkshopActivity_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CleaningStatus;
    serviceType: _ServiceType;
    contact: _ContactInfo;
    clientName: string;
    scheduledTime: _Time;
    employeeId: string;
    notes: string;
    price: bigint;
}): {
    id: string;
    status: CleaningStatus;
    serviceType: ServiceType;
    contact: ContactInfo;
    clientName: string;
    scheduledTime: Time;
    employeeId: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CleaningStatus_n31(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n33(_uploadFile, _downloadFile, value.serviceType),
        contact: value.contact,
        clientName: value.clientName,
        scheduledTime: value.scheduledTime,
        employeeId: value.employeeId,
        notes: value.notes,
        price: value.price
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactInfo: _ContactInfo;
    name: string;
    role: _Role;
}): {
    id: string;
    contactInfo: ContactInfo;
    name: string;
    role: Role;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        role: from_candid_Role_n38(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RestorationStatus;
    completionDate: _Time;
    cost: bigint;
    description: string;
    comments: string;
    clientContact: _ContactInfo;
    assignedEmployee: [] | [string];
}): {
    id: string;
    status: RestorationStatus;
    completionDate: Time;
    cost: bigint;
    description: string;
    comments: string;
    clientContact: ContactInfo;
    assignedEmployee?: string;
} {
    return {
        id: value.id,
        status: from_candid_RestorationStatus_n43(_uploadFile, _downloadFile, value.status),
        completionDate: value.completionDate,
        cost: value.cost,
        description: value.description,
        comments: value.comments,
        clientContact: value.clientContact,
        assignedEmployee: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.assignedEmployee))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    participants: Array<_Participant>;
    topic: string;
    scheduledTime: _Time;
    instructor: string;
    type: _WorkshopType;
    details: string;
    price: bigint;
}): {
    id: string;
    participants: Array<Participant>;
    topic: string;
    scheduledTime: Time;
    instructor: string;
    type: WorkshopType;
    details: string;
    price: bigint;
} {
    return {
        id: value.id,
        participants: value.participants,
        topic: value.topic,
        scheduledTime: value.scheduledTime,
        instructor: value.instructor,
        type: from_candid_WorkshopType_n49(_uploadFile, _downloadFile, value.type),
        details: value.details,
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    pending: null;
} | {
    completed: null;
}): CleaningStatus {
    return "scheduled" in value ? CleaningStatus.scheduled : "pending" in value ? CleaningStatus.pending : "completed" in value ? CleaningStatus.completed : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deepClean: null;
} | {
    standardClean: null;
} | {
    other: string;
} | {
    woodPolishing: null;
} | {
    upholsteryClean: null;
}): {
    __kind__: "deepClean";
    deepClean: null;
} | {
    __kind__: "standardClean";
    standardClean: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "woodPolishing";
    woodPolishing: null;
} | {
    __kind__: "upholsteryClean";
    upholsteryClean: null;
} {
    return "deepClean" in value ? {
        __kind__: "deepClean",
        deepClean: value.deepClean
    } : "standardClean" in value ? {
        __kind__: "standardClean",
        standardClean: value.standardClean
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "woodPolishing" in value ? {
        __kind__: "woodPolishing",
        woodPolishing: value.woodPolishing
    } : "upholsteryClean" in value ? {
        __kind__: "upholsteryClean",
        upholsteryClean: value.upholsteryClean
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    sales: null;
} | {
    cleaner: null;
} | {
    woodworker: null;
} | {
    restorer: null;
}): Role {
    return "manager" in value ? Role.manager : "admin" in value ? Role.admin : "sales" in value ? Role.sales : "cleaner" in value ? Role.cleaner : "woodworker" in value ? Role.woodworker : "restorer" in value ? Role.restorer : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): RestorationStatus {
    return "pending" in value ? RestorationStatus.pending : "completed" in value ? RestorationStatus.completed : "inProgress" in value ? RestorationStatus.inProgress : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kids: null;
} | {
    adults: null;
} | {
    skillLevel: null;
}): WorkshopType {
    return "kids" in value ? WorkshopType.kids : "adults" in value ? WorkshopType.adults : "skillLevel" in value ? WorkshopType.skillLevel : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CleaningAppointment>): Array<CleaningAppointment> {
    return value.map((x)=>from_candid_CleaningAppointment_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestorationProject>): Array<RestorationProject> {
    return value.map((x)=>from_candid_RestorationProject_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkshopActivity>): Array<WorkshopActivity> {
    return value.map((x)=>from_candid_WorkshopActivity_n47(_uploadFile, _downloadFile, x));
}
function to_candid_CleaningAppointment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CleaningAppointment): _CleaningAppointment {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CleaningStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CleaningStatus): _CleaningStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RestorationProject_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestorationProject): _RestorationProject {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RestorationStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestorationStatus): _RestorationStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_WorkshopActivity_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkshopActivity): _WorkshopActivity {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_WorkshopType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkshopType): _WorkshopType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactInfo: ContactInfo;
    name: string;
    role: Role;
}): {
    id: string;
    contactInfo: _ContactInfo;
    name: string;
    role: _Role;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: RestorationStatus;
    completionDate: Time;
    cost: bigint;
    description: string;
    comments: string;
    clientContact: ContactInfo;
    assignedEmployee?: string;
}): {
    id: string;
    status: _RestorationStatus;
    completionDate: _Time;
    cost: bigint;
    description: string;
    comments: string;
    clientContact: _ContactInfo;
    assignedEmployee: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_RestorationStatus_n20(_uploadFile, _downloadFile, value.status),
        completionDate: value.completionDate,
        cost: value.cost,
        description: value.description,
        comments: value.comments,
        clientContact: value.clientContact,
        assignedEmployee: value.assignedEmployee ? candid_some(value.assignedEmployee) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    participants: Array<Participant>;
    topic: string;
    scheduledTime: Time;
    instructor: string;
    type: WorkshopType;
    details: string;
    price: bigint;
}): {
    id: string;
    participants: Array<_Participant>;
    topic: string;
    scheduledTime: _Time;
    instructor: string;
    type: _WorkshopType;
    details: string;
    price: bigint;
} {
    return {
        id: value.id,
        participants: value.participants,
        topic: value.topic,
        scheduledTime: value.scheduledTime,
        instructor: value.instructor,
        type: to_candid_WorkshopType_n24(_uploadFile, _downloadFile, value.type),
        details: value.details,
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: CleaningStatus;
    serviceType: ServiceType;
    contact: ContactInfo;
    clientName: string;
    scheduledTime: Time;
    employeeId: string;
    notes: string;
    price: bigint;
}): {
    id: string;
    status: _CleaningStatus;
    serviceType: _ServiceType;
    contact: _ContactInfo;
    clientName: string;
    scheduledTime: _Time;
    employeeId: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: to_candid_CleaningStatus_n10(_uploadFile, _downloadFile, value.status),
        serviceType: to_candid_ServiceType_n12(_uploadFile, _downloadFile, value.serviceType),
        contact: value.contact,
        clientName: value.clientName,
        scheduledTime: value.scheduledTime,
        employeeId: value.employeeId,
        notes: value.notes,
        price: value.price
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CleaningStatus): {
    scheduled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == CleaningStatus.scheduled ? {
        scheduled: null
    } : value == CleaningStatus.pending ? {
        pending: null
    } : value == CleaningStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "deepClean";
    deepClean: null;
} | {
    __kind__: "standardClean";
    standardClean: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "woodPolishing";
    woodPolishing: null;
} | {
    __kind__: "upholsteryClean";
    upholsteryClean: null;
}): {
    deepClean: null;
} | {
    standardClean: null;
} | {
    other: string;
} | {
    woodPolishing: null;
} | {
    upholsteryClean: null;
} {
    return value.__kind__ === "deepClean" ? {
        deepClean: value.deepClean
    } : value.__kind__ === "standardClean" ? {
        standardClean: value.standardClean
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "woodPolishing" ? {
        woodPolishing: value.woodPolishing
    } : value.__kind__ === "upholsteryClean" ? {
        upholsteryClean: value.upholsteryClean
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    manager: null;
} | {
    admin: null;
} | {
    sales: null;
} | {
    cleaner: null;
} | {
    woodworker: null;
} | {
    restorer: null;
} {
    return value == Role.manager ? {
        manager: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.sales ? {
        sales: null
    } : value == Role.cleaner ? {
        cleaner: null
    } : value == Role.woodworker ? {
        woodworker: null
    } : value == Role.restorer ? {
        restorer: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestorationStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == RestorationStatus.pending ? {
        pending: null
    } : value == RestorationStatus.completed ? {
        completed: null
    } : value == RestorationStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkshopType): {
    kids: null;
} | {
    adults: null;
} | {
    skillLevel: null;
} {
    return value == WorkshopType.kids ? {
        kids: null
    } : value == WorkshopType.adults ? {
        adults: null
    } : value == WorkshopType.skillLevel ? {
        skillLevel: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
